# -*- coding: utf-8 -*-
"""yolo12tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OkmXVOOhqdhsz75hqHWpvYbt7Af4wly
"""

# Ultralytics YOLO를 사용한 다중 객체 추적
# Ultralytics YOLO 기반 트래킹은 영상에서 객페를 탐지 + ID를 붙여 물체를 계속 추적하는 기술
# 2단계로 작업
# - Detection : 사람 / 동물 / 자동차 등 감지
# - Tracking : 같은 객체에 id를 부여해 프레임이 바뀌어도 동일 객체 유지

# !pip install ultralytics

import cv2
from ultralytics import YOLO
# from google.colab.patches import cv2_imshow # Added for Colab compatibility

model = YOLO("yolo11n.pt")

video_path = "road_car.mp4"

cap = cv2.VideoCapture(video_path)  # 지정한 동영상 파일을 프레임 단위로 읽기

if not cap.isOpened():
  print('동영상 열기 실패')
  exit()

while True:
  ret, frame = cap.read()  #  ret : 읽기 성공 여부  /  frame : 실제 이미지 데이터


  if not ret:
    break

  results = model.track(
      source = frame,
      persist = True,
      tracker = "bytetrack.yaml",  # 객체 추적 알고리즘
      verbose = False,
      show = False,
  )

  result = results[0]

  if result.boxes is not None and result.boxes.id is not None:
    boxes = result.boxes.xywh.cpu().numpy()
    ids = result.boxes.id.cpu().numpy().astype(int)
    class_ids = result.boxes.cls.cpu().numpy().astype(int)

    for box, track_id, class_id in zip(boxes, ids, class_ids):
      x1, y1, x2, y2 = map(int, box)
      class_name = result.names[class_id]
      print(f"id : {track_id} class : {class_name} box : ", x1,y1,x2,y2)

  annotated_frame = result.plot()  # yolo가 탐지한 이미지 자동으로 그리기 (각종 정보가 표시됨)

  display_frame = cv2.resize(annotated_frame, (960, 540))

  cv2.imshow("YOLO Tracking", display_frame) # Changed cv2.imshow to cv2_imshow

  if cv2.waitKey(1) & 0xFF == ord("q"):  # 0xFF : 16진수로 숫자 255를 의미합니다.
    break

cap.release()
cv2.destroyAllWindows()