# -*- coding: utf-8 -*-
"""cnn16quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXvsTm5X65eQcHVvOc7XUw8rhoaX7h1C
"""

'''
문제6) 이미지 분류

CIFAR-100 dataset 사용    ( 얘 말고 다른 데이터를 이용해도 됨. 음식, 사무용 집기, 라면(우동) ... )
특징
 - 클래스 수: 100개 (예: 사과, 버스, 산, 고래, 시계 등)
 - 샘플 수: 60,000장, 학습용(train): 50,000장, 테스트용(test): 10,000장
 - 이미지 크기: 32×32 RGB (작은 해상도)
 - 레이블 구조: 100개 fine labels (세부 클래스), 20개 coarse labels (상위 클래스 그룹)

기본 CNN으로도 학습 가능하지만, 성능을 높이려면
 - 데이터 증강(ImageDataGenerator / tf.image)
 - 전이학습(사전학습 모델)
 - 정규화/드롭아웃/배치정규화 등을 함께 쓰는 게 효과적


-- 전체 흐름 요약 --

  작업1 :  CIFAR-100 dataset  분류 모델 작성 (MovileNetV2 모델로 전이학습, 파인튜닝)
  작업2 : 작성한  분류 모델 사용

              웹 브라우저에서 이미지 선택
                   → 장고 웹서버에 저장 → 서버 내부에서 시각화로 확인(matplotlib) + 딥러닝 분류

                  → 클라이언트에 분류 결과만 반환하기

작업2를 좀더 구체적으로 보면
 1) 클라이언트
    : index.html에서 파일선택 버튼을 눌러 로컬 컴퓨터의 이미지 파일을 선택하고 화면에 선택된 이미지 출력
    : 분류결과요청 버튼 클릭 → AJAX 전송 (axios 모듈 사용)
 2) 서버(Django)
    : 수신된 이미지 파일 저장 → PIL + Matplotlib(imshow)으로 확인 → 딥러닝 분류 모델로 추론
    : 응답(JSON): 분류 결과만 반환(예 : bus)
 3) 클라이언트
    : 기존 이미지 아래에 이미지 분류 결과 문자열을 화면에 출력
'''

# 학습된 대형모델(백본)인 MobileNet v2를 전이학습하여 cifar100 dataset을 분류하기
# 전이학습(Transfrer Learning) - 이미 학습된 모델을 일부 재학습하여

import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar100.load_data()

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

NUM_CLASSES = 100
y_train = tf.keras.utils.to_categorical(y_train, NUM_CLASSES) # 원핫인코딩
y_test = tf.keras.utils.to_categorical(y_test, NUM_CLASSES)

print('train data : ', x_train.shape, y_train.shape)          # (50000, 32, 32, 3) (50000, 100)
print('test data : ', x_test.shape, y_test.shape)             # (10000, 32, 32, 3) (10000, 100)

# 전이학습 : 기존 모델(백본)의 가중치는 모두 동결(freeze)
base_model = tf.keras.applications.MobileNetV2(
    input_shape = (128, 128, 3),    # 입력 크기 96, 128, 160, 192, 224 등을 지원
    include_top = False,    # MobileNetV2의 분류기 부분을 뺌, 컨볼루션 레이어만 남김
    weights = 'imagenet'    # 사전 학습된 가중치 호출(120만 이미지, 1000개의 클래스)
)

base_model.trainable = False  #  MobileNetV2은 학습에 참여 하지 않도록 동결

print(base_model.summary())
#  Total params: 2,257,984 (8.61 MB)
#  Trainable params: 0 (0.00 B)
#  Non-trainable params: 2,257,984 (8.61 MB)

# MobileNetV2 을 이용해 새로운 모델 생성
inputs = tf.keras.Input(shape = (32, 32, 3))
x = tf.keras.layers.Resizing(128, 128)(inputs)           # cifar10 이미지를 MobileNetV2에 맞게 리사이징
x = base_model(x, training = False)
x = tf.keras.layers.GlobalAveragePooling2D()(x) # MaxPooling2D 보다 더 급격하게 feature의 크기를 줄임
output = tf.keras.layers.Dense(units=NUM_CLASSES, activation = 'softmax')(x)

model_tl = tf.keras.Model(inputs = inputs, outputs = output)
print(model_tl.summary())

model_tl.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model_tl.fit(x_train, y_train, epochs=10, batch_size=64, validation_split=0.2, verbose=2)

loss, acc = model_tl.evaluate(x_test, y_test, verbose=0)
print(f'loss :{loss:.4f}, acc : {acc:.4f}')

# 미세 조정 (Fine Tunning) - 전이 학습 이후 성능 항상을 위해 백본의 일부 층을 학습에 참여시킴
EPOCHS_TL = 10
EPOCHS_FT = 20

base_model.trainable = True
for layer in base_model.layers[:-10]:
    layer.trainable = False

model_tl.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
                 loss='categorical_crossentropy', metrics=['accuracy'])

history_ft = model_tl.fit(
    x_train, y_train,
    initial_epoch=EPOCHS_TL,  # 10부터
    epochs=EPOCHS_FT,         # 20까지
    batch_size=64, validation_split=0.2, verbose=2
)


loss, acc = model_tl.evaluate(x_test, y_test, verbose=0)
print(f'loss :{loss:.4f}, acc : {acc:.4f}')

# 시각화를 통한 테스트 성능 비교
import matplotlib.pyplot as plt

def concat_history(h1, h2):
  keys = h1.history.keys()
  out = {}
  for k in keys:
    out[k] = h1.history[k] + h2.history[k]  # 각 key(loss, acc)에 대해 리스트에 이어 붙임
  return out

hist_all = concat_history(history, history_ft)
acc = hist_all['accuracy']
val_acc = hist_all['val_accuracy']
loss = hist_all['loss']
val_loss = hist_all['val_loss']

epochs = range(1, len(acc) + 1)
split_epoch = EPOCHS_TL   # 전이학습과 미세조정 경계선 위치

plt.figure(figsize = (12, 5))
# acc
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, marker='o', label='train acc')
plt.plot(epochs, val_acc, marker='s', label='val acc')

for i, v in enumerate(acc):
  plt.text(epochs[i], v, f'{v * 100:.1f}%', ha='center', va='bottom', fontsize=9)

for i,v in enumerate(val_acc):
  plt.text(epochs[i], v, f'{v * 100:.1f}%', ha='center', va='top', fontsize=9)

# 전이 -> 미세조정 전환선
plt.axvline(x=split_epoch, linestyle='--', alpha=0.7, label='fine tunning start')
plt.title('Accuracy(transfer -> fine tunning)')
plt.xlabel('epoch')
plt.ylabel('acc')
plt.legend(loc='lower right')

# loss
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, marker='o', label='train loss')
plt.plot(epochs, val_loss, marker='s', label='val loss')

for i, v in enumerate(loss):
  plt.text(epochs[i], v, f'{v:.3f}', ha='center', va='bottom', fontsize=9)

for i,v in enumerate(val_loss):
  plt.text(epochs[i], v, f'{v:.3f}', ha='center', va='top', fontsize=9)

plt.title('Loss(transfer -> fine tunning)')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend(loc='upper right')

plt.tight_layout()
plt.show()

# 모델 저장
model_tl.save('cifar100_mobilenetv2.keras')